DMS/Controllers/Configurations/BranchController.cs
using AutoMapper;
using DMS.Extensions;
using DMS.Model;
using DMS.Models;
using DMS.RestHelpers;
using log4net;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace DMS.Controllers.Configurations
{
    public class BranchController : Controller
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(BranchController));
        // GET: Branch
        public ActionResult Index()
        {
            using (BranchProfileRestHelper restHelper = new BranchProfileRestHelper())
            {
                IList<Branch> branchProfiles = new List<Branch>();
                var response = restHelper.GetBranchProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    branchProfiles = JsonConvert.DeserializeObject<List<Branch>>(response.Content);
                    return View(branchProfiles);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View(branchProfiles);
                }
            }

        }


        // GET: Branch/Create
        public ActionResult Create()
        {
            using (CompanyProfileRestHelper restHelper = new CompanyProfileRestHelper())
            {
                var response = restHelper.GetCompanyProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    BranchViewModel branchViewModel = new BranchViewModel
                    {
                        CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content)
                    };
                    return View(branchViewModel);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View("Index");
                }
               
            }
        }

        // POST: Branch/Create
        [HttpPost]
        public ActionResult Create(BranchViewModel branchViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (BranchProfileRestHelper restHelper = new BranchProfileRestHelper())
                    {


                        var config = new MapperConfiguration(cfg => cfg.CreateMap<BranchViewModel, Branch>());
                        var mapper = config.CreateMapper();
                        Branch branch = mapper.Map<Branch>(branchViewModel);

                        var response= restHelper.AddBranchProfile(branch);

                        if(response.StatusCode==HttpStatusCode.OK)
                        {
                            this.AddNotification("Branch profile created successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("Branch profile:{0} created successfully.",branch.Name));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Error(string.Format("Error occured while creating Branch profile:{0} Exceprion:", branch.Name,response.Content));
                        }

                    }

                   
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification("Some fields are required", NotificationType.WARNING);

                    CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper();
                    var response= companyProfileRestHelper.GetCompanyProfiles();
                    if (response.StatusCode == HttpStatusCode.OK)
                        branchViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);

                    return View("Create", branchViewModel);
                }


            }
            catch (Exception)
            {
                return View();
            }
        }        // GET: Branch/Edit/5
        public ActionResult Edit(int id)
        {
            using (BranchProfileRestHelper restHelper = new BranchProfileRestHelper())
            {
                Branch branch = restHelper.GetBranchProfileById(id);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Branch, BranchViewModel>());
                var mapper = config.CreateMapper();
                BranchViewModel branchViewModel = mapper.Map<BranchViewModel>(branch);
                using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                {
                    var response= companyProfileRestHelper.GetCompanyProfiles();
                    if(response.StatusCode==HttpStatusCode.OK)
                    branchViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);

                }
                return View(branchViewModel);
            }
        }

        // POST: Branch/Edit/5
        [HttpPost]
        public ActionResult Edit(BranchViewModel branchViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (BranchProfileRestHelper branchProfileRestHelper = new BranchProfileRestHelper())
                    {
                        var config = new MapperConfiguration(cfg => cfg.CreateMap<BranchViewModel, Branch>());
                        var mapper = config.CreateMapper();
                        Branch branch = mapper.Map<Branch>(branchViewModel);

                        var response= branchProfileRestHelper.UpdateBranchProfile(branch);
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            this.AddNotification("Branch profile updated successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("Branch profile:{0} updated successfully.",branch.Name));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Error(string.Format("Error occured while updating branch:{0} Exception:",branch.Name,response.Content));
                        }
                    }                    

                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification("Error while update Branch Profile:" + ex.Message, NotificationType.ERROR);
                Logger.Error("Error while update Branch Profile:" + ex.Message);
                return View();
            }
        }


        public ActionResult Delete(int id)
        {


            using (BranchProfileRestHelper branchProfileRestHelper = new BranchProfileRestHelper())
            {
                var response = branchProfileRestHelper.DeleteBranchProfileById(id);
                if (response.StatusCode==HttpStatusCode.OK)
                {
                    this.AddNotification("Branch profile deleted successfully!", NotificationType.SUCCESS);
                    Logger.Info("Branch profile deleted successfully!");
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    Logger.Error("Error occured while deleting branch profile:" + response.Content);
                    return RedirectToAction("Index");
                }
            }


        }
    }
}

DMS/Controllers/Configurations/UserController.cs
using AutoMapper;
using DMS.Extensions;
using DMS.Model;
using DMS.Models;
using DMS.RestHelpers;
using log4net;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace DMS.Controllers.Configurations
{
    public class UserController : Controller
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(UserController));
        // GET: User
        public ActionResult Index()
        {
            using (UserRestHelper restHelper = new UserRestHelper())
            {
                IList<Users> userProfiles = new List<Users>();
                var response = restHelper.GetAllUserProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    userProfiles = JsonConvert.DeserializeObject<List<Users>>(response.Content);
                    return View(userProfiles);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View(userProfiles);
                }
            }

        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                var companyResponse = companyProfileRestHelper.GetCompanyProfiles();

                using (BranchProfileRestHelper branchProfileRestHelper = new BranchProfileRestHelper())
                {
                    var branchResponse = branchProfileRestHelper.GetBranchProfiles();

                    if (companyResponse.StatusCode == HttpStatusCode.OK && branchResponse.StatusCode == HttpStatusCode.OK)
                    {
                        UserViewModel userViewModel = new UserViewModel
                        {
                            CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(companyResponse.Content),
                            Branches = JsonConvert.DeserializeObject<List<Branch>>(branchResponse.Content)

                        };
                        return View(userViewModel);
                    }
                }


            }
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(UserViewModel userViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UserRestHelper userRestHelper = new UserRestHelper())
                    {
                        var config = new MapperConfiguration(cfg => cfg.CreateMap<UserViewModel, Users>());
                        var mapper = config.CreateMapper();
                        Users users = mapper.Map<Users>(userViewModel);

                        var response = userRestHelper.AddUser(users);
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            this.AddNotification("User profile created successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("User profile:{0} created successfully.", users.LoginName));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Error(string.Format("Error occured while creating User profile:{0} Exceprion:", users.LoginName, response.Content));
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                var companyResponse = companyProfileRestHelper.GetCompanyProfiles();

                using (BranchProfileRestHelper branchProfileRestHelper = new BranchProfileRestHelper())
                {
                    var branchResponse = branchProfileRestHelper.GetBranchProfiles();

                    if (companyResponse.StatusCode == HttpStatusCode.OK && branchResponse.StatusCode == HttpStatusCode.OK)
                    {
                        using (UserRestHelper userRestHelper = new UserRestHelper())
                        {
                            Users users = userRestHelper.GetUserProfileById(id);
                            var config = new MapperConfiguration(cfg => cfg.CreateMap<Users, UserViewModel>());
                            var mapper = config.CreateMapper();
                            UserViewModel userViewModel = mapper.Map<UserViewModel>(users);
                            userViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(companyResponse.Content);
                            userViewModel.Branches = JsonConvert.DeserializeObject<List<Branch>>(branchResponse.Content);
                            return View(userViewModel);
                        }

                    }
                }


            }
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(UserViewModel userViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UserRestHelper userRestHelper = new UserRestHelper())
                    {
                        var config = new MapperConfiguration(cfg => cfg.CreateMap<UserViewModel, Users>());
                        var mapper = config.CreateMapper();
                        Users users = mapper.Map<Users>(userViewModel);

                        var response = userRestHelper.UpdateUserProfile(users);
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            this.AddNotification("User profile updated successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("User profile:{0} updated successfully.", users.LoginName));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Error(string.Format("Error occured while creating User profile:{0} Exceprion:", users.LoginName, response.Content));
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            using (UserRestHelper userRestHelper = new UserRestHelper())
            {
                var response = userRestHelper.DeleteUserProfileById(id);
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    this.AddNotification("User profile deleted successfully!", NotificationType.SUCCESS);
                    Logger.Info("User profile deleted successfully!");
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    Logger.Error("Error occured while deleting user profile:" + response.Content);
                    return RedirectToAction("Index");
                }
            }

        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="app-ui">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Document Management System</title>
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="~/assets/img/favicons/apple-touch-icon.png" />
    <link rel="icon" href="~/assets/img/favicons/favicon.ico" />
    <!-- Google fonts -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,900%7CRoboto+Slab:300,400%7CRoboto+Mono:400" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="app-ui layout-has-drawer layout-has-fixed-header">
    <div class="app-layout-canvas">
        <div class="app-layout-container">
            <!-- Drawer -->
            <aside class="app-layout-drawer">
                <!-- Drawer scroll area -->
                <div class="app-layout-drawer-scroll">
                    <!-- Drawer logo -->
                    <div id="logo" class="drawer-header">
                        <a href="@Url.Action("Index","Home")"><img class="img-responsive" src="~/assets/img/logo/logo-backend.png" title="DMS" alt="DMS" /></a>
                    </div>
                    <!-- Drawer navigation -->
                    <nav class="drawer-main">
                        <ul class="nav nav-drawer">
                            <li class="nav-item nav-drawer-header">Apps</li>
                            <li class="nav-item active">
                                <a href="@Url.Action("Index","Home")"><i class="ion-ios-speedometer-outline"></i> Dashboard</a>
                            </li>

                            <li class="nav-item nav-drawer-header">Configurations</li>
                            <li class="nav-item nav-item-has-subnav">
                                <a href="javascript:void(0)"><i class="ion-ios-calculator-outline"></i>Configurations</a>
                                <ul class="nav nav-subnav">
                                    <li>
                                        <a href="@Url.Action("Index","Branch")" class="ion-ios-arrow-thin-right"> Branch Profiles</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","CompanyProfile")" class="ion-ios-arrow-thin-right"> Company Profiles</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Department")" class="ion-ios-arrow-thin-right"> Departments</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","User")" class="ion-ios-arrow-thin-right"> User Profiles</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                    <!-- End drawer navigation -->

                </div>
                <!-- End drawer scroll area -->
            </aside>
            <!-- End drawer -->
            <!-- Header -->
            <header class="app-layout-header">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar-collapse" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <button class="pull-left hidden-lg hidden-md navbar-toggle" type="button" data-toggle="layout" data-action="sidebar_toggle">
                                <span class="sr-only">Toggle drawer</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <span class="navbar-page-title">

                                Dashboard
                            </span>
                        </div>
                        <div class="collapse navbar-collapse" id="header-navbar-collapse">
                            <!-- Header search form -->
                            <form class="navbar-form navbar-left app-search-form" role="search">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input class="form-control" type="search" id="search-input" placeholder="Search..." />
                                        <span class="input-group-btn">
                                            <button class="btn" type="button"><i class="ion-ios-search-strong"></i></button>
                                        </span>
                                    </div>
                                </div>
                            </form>

                            <!-- .navbar-left -->
                            <ul class="nav navbar-nav navbar-right navbar-toolbar hidden-sm hidden-xs">
                                <li>
                                    <!-- Opens the modal found at the bottom of the page -->
                                    @*<a href="javascript:void(0)" data-toggle="modal" data-target="#apps-modal"><i class="ion-grid"></i></a>*@
                                </li>
                                <li class="dropdown">
                                    <a href="javascript:void(0)" data-toggle="dropdown"><i class="ion-ios-bell"></i> <span class="badge">3</span></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li class="dropdown-header">Profile</li>
                                        <li>
                                            <a tabindex="-1" href="javascript:void(0)"><span class="badge pull-right">3</span> News </a>
                                        </li>
                                        <li>
                                            <a tabindex="-1" href="javascript:void(0)"><span class="badge pull-right">1</span> Messages </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">More</li>
                                        <li>
                                            <a tabindex="-1" href="javascript:void(0)">Edit Profile..</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown dropdown-profile">
                                    <a href="javascript:void(0)" data-toggle="dropdown">
                                        <span class="m-r-sm">John Doe <span class="caret"></span></span>
                                        <img class="img-avatar img-avatar-48" src="~/assets/img/avatars/avatar3.jpg" alt="User profile pic" />
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li class="dropdown-header">
                                            Pages
                                        </li>
                                        <li>
                                            <a href="base_pages_profile.html">Profile</a>
                                        </li>
                                        <li>
                                            <a href="base_pages_profile.html"><span class="badge badge-success pull-right">3</span> Blog</a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Logout","Login")">Logout</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- .navbar-right -->
                        </div>
                    </div>
                    <!-- .container-fluid -->
                </nav>
                <!-- .navbar-default -->
            </header>
            <!-- End header -->
            <main class="app-layout-content">
                <!-- Page Content -->
                @Html.Partial("_Notifications")
                @RenderBody()
                <!-- .container-fluid -->
                <!-- End Page Content -->
            </main>
        </div>
        <!-- .app-layout-container -->
    </div>
    <!-- .app-layout-canvas -->
    <!-- Apps Modal -->
    <!-- Opens from the button in the header -->
    <div id="apps-modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-sm modal-dialog modal-dialog-top">
            <div class="modal-content">
                <!-- Apps card -->
                <div class="card m-b-0">
                    <div class="card-header bg-app bg-inverse">
                        <h4>Apps</h4>
                        <ul class="card-actions">
                            <li>
                                <button data-dismiss="modal" type="button"><i class="ion-close"></i></button>
                            </li>
                        </ul>
                    </div>
                    <div class="card-block">
                        <div class="row text-center">
                            <div class="col-xs-6">
                                <a class="card card-block m-b-0 bg-app-secondary bg-inverse" href="index.html">
                                    <i class="ion-speedometer fa-4x"></i>
                                    <p>Admin</p>
                                </a>
                            </div>
                            <div class="col-xs-6">
                                <a class="card card-block m-b-0 bg-app-tertiary bg-inverse" href="frontend_home.html">
                                    <i class="ion-laptop fa-4x"></i>
                                    <p>Frontend</p>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- .card-block -->
                </div>
                <!-- End Apps card -->
            </div>
        </div>
    </div>
    <!-- End Apps Modal -->
    <div class="app-ui-mask-modal"></div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("Head", required: false);

</body>
</html>

DMS/Views/Shared/_LayoutPageLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Meta -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <!-- Document title -->
    <title>Login | DMS</title>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="~/assets/img/favicons/apple-touch-icon.png" />
    <link rel="icon" href="~/assets/img/favicons/favicon.ico" />
    
    <!-- AppUI CSS stylesheets -->
    <link rel="stylesheet" id="css-font-awesome" href="~/assets/css/font-awesome.css" />
    <link rel="stylesheet" id="css-ionicons" href="~/assets/css/ionicons.css" />
    <link rel="stylesheet" id="css-bootstrap" href="~/assets/css/bootstrap.css" />
    <link rel="stylesheet" id="css-app" href="~/assets/css/app.css" />
    <link rel="stylesheet" id="css-app-custom" href="~/assets/css/app-custom.css" />
    <!-- End Stylesheets -->
</head>
<body class="app-ui">
    <div class="app-layout-canvas">
        <div class="app-layout-container">
            <main class="app-layout-content">

                <!-- Page content -->
                <div class="page-content">
                    <div class="container">
                        <div class="row">
                            <!-- Login card -->
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-5">
                                <div class="card">
                                    <h3 class="card-header h4">Login</h3>
                                    @Html.Partial("_Notifications")
                                    @RenderBody()
                                </div>
                                <!-- .card -->
                            </div>
                            <!-- .col-md-6 -->
                            <!-- End login -->

                        </div>
                        <!-- .row -->
                    </div>
                    <!-- .container -->
                </div>
                <!-- End page content -->

            </main>

        </div>

        <!-- .app-layout-container -->
    </div>
    
    <!-- .app-layout-canvas -->
    <!-- AppUI Core JS: jQuery, Bootstrap, slimScroll, scrollLock and App.js -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/core/jquery.slimscroll.min.js"></script>
    <script src="~/assets/js/core/jquery.scrollLock.min.js"></script>
    <script src="~/assets/js/core/jquery.placeholder.min.js"></script>
    <script src="~/assets/js/app.js"></script>
    <script src="~/assets/js/app-custom.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("Head", required: false);
</body>
</html>