DMS/Models/CompanyProfileViewModel.cs
using DMS.Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DMS.Models
{
    public class CompanyProfileViewModel
    {
        [JsonProperty("Id")]
        public long Id { get; set; }

        [JsonProperty("Name")]
        [Required(ErrorMessage="Please enter name"),MaxLength(130)]
        public string Name { get; set; }

        [JsonProperty("DisplayName")]
        [Display(Name = "Display Name")]
        [Required(ErrorMessage = "Please enter Display Name"), MaxLength(30)]
        public string DisplayName { get; set; }

        [JsonProperty("IsParent")]
        public bool IsParent { get; set; }

        
        [JsonProperty("ParentId")]
        public long ParentId { get; set; }

        [Display(Name = "Company Logo")]
        [JsonProperty("CompanyLogoPath")]
        public string CompanyLogoPath { get; set; }

        [JsonProperty("CompanyId")]
        public string CompanyId { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Phone")]
        public string Phone { get; set; }

        [JsonProperty("Fax")]
        public string Fax { get; set; }

        [JsonProperty("WebAddress")]
        [Display(Name = "Web Address")]
        public string WebAddress { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Creatorid")]
        public long Creatorid { get; set; }

        [JsonProperty("UpdatorId")]
        public long UpdatorId { get; set; }

        public IList<CompanyProfile> CompanyProfiles { get; set; }
    }
}

DMS/Controllers/Configurations/CompanyProfileController.cs
using AutoMapper;
using DMS.Extensions;
using DMS.Model;
using DMS.Models;
using DMS.RestHelpers;
using log4net;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DMS.Controllers.Configurations
{
    public class CompanyProfileController : Controller
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(CompanyProfileController));
        public CompanyProfileController()
        {

        }
        // GET: CompanyProfile
        public ActionResult Index()
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                List<CompanyProfile> companyProfiles = new List<CompanyProfile>();
                var response = companyProfileRestHelper.GetCompanyProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    companyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);
                }
                return View(companyProfiles);
            }
        }

        public ActionResult Create()
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                
                CompanyProfileViewModel companyviewModel = new CompanyProfileViewModel();
                var response = companyProfileRestHelper.GetCompanyProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    companyviewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);
                    return View(companyviewModel);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View("Index");
                }
                
            }
        }

        [HttpPost]
        public ActionResult Create(CompanyProfileViewModel _model, HttpPostedFileBase file)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                    {
                        var config = new MapperConfiguration(cfg => cfg.CreateMap<CompanyProfileViewModel, CompanyProfile>());
                        var mapper = config.CreateMapper();
                        CompanyProfile companyProfile = mapper.Map<CompanyProfile>(_model);
                        if (file != null)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                            var filePath = "~/App_Data/uploads/" + fileName;
                            companyProfile.CompanyLogoPath = filePath;
                            file.SaveAs(path);
                        }
                        var response = companyProfileRestHelper.AddCompanyProfile(companyProfile);
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            this.AddNotification("Company profile created successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("Company {0} created successfully.", companyProfile.Name));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Error("Error occured while creating company profile:" + response.Content);
                        }
                    }



                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification("Some fields are required", NotificationType.WARNING);
                    using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                    {
                        var response= companyProfileRestHelper.GetCompanyProfiles();
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            _model.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);
                            
                        }
                       
                    }
                    return View("Create", _model);
                }


            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                CompanyProfile companyProfile = companyProfileRestHelper.GetCompanyProfileById(id);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<CompanyProfile, CompanyProfileViewModel>());
                var mapper = config.CreateMapper();
                CompanyProfileViewModel companyProfileViewModel = mapper.Map<CompanyProfileViewModel>(companyProfile);

                var response = companyProfileRestHelper.GetCompanyProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    companyProfileViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);
                    return View(companyProfileViewModel);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View("Index");
                }
              
            }
        }

        [HttpPost]
        public ActionResult Edit(CompanyProfileViewModel companyProfileViewModel, HttpPostedFileBase file)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                    {
                        string filePath = string.Empty;
                        if (file != null)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                            filePath = "~/App_Data/uploads/" + fileName;
                            file.SaveAs(path);
                        }
                        var config = new MapperConfiguration(cfg => cfg.CreateMap<CompanyProfileViewModel, CompanyProfile>());
                        var mapper = config.CreateMapper();
                        CompanyProfile companyProfile = mapper.Map<CompanyProfile>(companyProfileViewModel);
                        companyProfile.CompanyLogoPath = file != null ? filePath : companyProfileViewModel.CompanyLogoPath;

                        var response = companyProfileRestHelper.UpdateCompanyProfile(companyProfile);
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            this.AddNotification("Company profile updated successfully!", NotificationType.SUCCESS);
                            Logger.Info(string.Format("Company profile:{0} updated successfully!",companyProfile.Name));
                        }
                        else
                        {
                            this.AddNotification(response.Content, NotificationType.ERROR);
                            Logger.Info(string.Format("Error occured while updating company profile:{0} Exception:",companyProfile.Name,response.Content));
                        }
                    }



                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification("Error while update company Profile:" + ex.Message, NotificationType.ERROR);
                Logger.Info(string.Format("Error occured while updating company profile Exception:{0}", ex.Message));
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add update logic here
                using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                {
                    var response = companyProfileRestHelper.DeleteCompanyProfileById(id);
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        this.AddNotification("Company profile deleted successfully!", NotificationType.SUCCESS);
                        Logger.Info(string.Format("Company profile deleted successfully."));
                    }
                    else
                    {
                        this.AddNotification(response.Content, NotificationType.ERROR);
                        Logger.Error("Error occured while deleting company profile:" + response.Content);
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
    }
}

DMS/Views/CompanyProfile/Create.cshtml
@model DMS.Models.CompanyProfileViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2.min.css" />
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2-bootstrap.css" />
<style type="text/css">
    .text-danger{
        color:red;
        font-size:smaller;
    }
</style>

@using (Html.BeginForm("Create", "CompanyProfile", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <!-- Horizontal Form -->
    <div class="card">
        <div class="card-header">
            <h4>Company Profile</h4>
            <ul class="card-actions">
                <li>
                    <button type="button"><i class="ion-more"></i></button>
                </li>
            </ul>
        </div>
        <div class="card-block">

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">

                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Company Name..." } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter display Name..." } })
                    @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsParent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.CheckBoxFor(model => model.IsParent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsParent, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Company</label>
                @*@Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.ParentId, new SelectList(Model.CompanyProfiles, "Id", "Name"), "Select Company", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.TextAreaFor(model => model.Address, new { @rows = "4", @class = "form-control", @placeholder = "Enter Company Address..." })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.WebAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Web Address..." } })
                    @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email Address..." } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.CompanyLogoPath, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <label class="control-label col-md-2">Comapany Logo</label>
                <div class="col-md-5">
                    @*@Html.TextBoxFor(model => model.CompanyLogoPath, new { type = "file", placeholder = Html.DisplayNameFor(m => m.CompanyLogoPath), @class = "form-control" })*@
                    <div class="col-md-10">
                        <input type="file" name="file" />
                    </div>
                    @Html.ValidationMessageFor(model => model.CompanyLogoPath, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group m-b-0">
                <div class="col-md-9 col-md-offset-3">
                    <button class="btn btn-app" type="submit">Save</button>
                    <a href="@Url.Action("Index")" class="btn btn-app-light">Cancel</a>
                </div>

            </div>

        </div>
    </div>
    <!-- End Horizontal Form -->
</div>
}


<script src="~/assets/js/core/jquery.min.js"></script>
<!-- Page JS Plugins -->

<!-- Page JS Code -->
<script>
    $(function () {

        $companySelectize = $("#ParentId").selectize();
        companySelectize = $companySelectize[0].selectize;
        $("#IsParent").click(function () {
            if ($("#IsParent").prop("checked") == true) {
                companySelectize.disable();
            }
            else {
                companySelectize.enable();
            }
        });
    });


</script>

DMS/Views/CompanyProfile/Edit.cshtml
@model DMS.Models.CompanyProfileViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="~/assets/js/plugins/select2/select2.min.css" />
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2-bootstrap.css" />

@using (Html.BeginForm("Edit", "CompanyProfile", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CompanyLogoPath)
    <div class="card">
        <div class="card-header">
            <h4>Company Profile</h4>
            <ul class="card-actions">
                <li>
                    <button type="button"><i class="ion-more"></i></button>
                </li>
            </ul>
        </div>
        <div class="card-block">
            <form class="form-horizontal" action="base_forms_elements.html" method="post" onsubmit="return false;">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-7">

                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Company Name..." } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter display Name..." } })
                        @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsParent, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.CheckBoxFor(model => model.IsParent, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsParent, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Company</label>
                    @*@Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.ParentId, new SelectList(Model.CompanyProfiles, "Id", "Name"), "Select Company", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Company Address..." } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.WebAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Web Address..." } })
                        @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email Address..." } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanyLogoPath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @*@Html.TextBoxFor(model => model.CompanyLogoPath, new { type = "file", placeholder = Html.DisplayNameFor(m => m.CompanyLogoPath), @class = "form-control" })*@
                        <div class="col-md-10">
                            <input type="file" name="file" />
                        </div>
                        @Html.ValidationMessageFor(model => model.CompanyLogoPath, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group m-b-0">
                    <div class="col-md-9 col-md-offset-3">
                        <button class="btn btn-app" type="submit">Save</button>
                        <button class="btn btn-app-light" type="submit">Cancel</button>
                    </div>

                </div>
            </form>
        </div>
    </div>

</div>
}

<script src="~/assets/js/core/jquery.min.js"></script>
<!-- Page JS Code -->
<script>
    $(function () {

        $companySelectize = $("#ParentId").selectize();
        companySelectize = $companySelectize[0].selectize;
        if ($("#IsParent").prop("checked") == true) {
            companySelectize.disable();
        }
        else {
            companySelectize.enable();
        }
        $("#IsParent").click(function () {
            if ($("#IsParent").prop("checked") == true) {
                companySelectize.disable();
            }
            else {
                companySelectize.enable();
            }
        });
    });


</script>

DMS/Views/CompanyProfile/Index.cshtml
@model IEnumerable<DMS.Model.CompanyProfile>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/assets/js/plugins/datatables/jquery.dataTables.min.css" />



<div class="card">
    <div class="card-header">
        <h4>Company Profiles</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md" style="margin-bottom:5px;">
                    <a href="@Url.Action("Create","CompanyProfile")" id="addToTable" class="btn btn-app-teal">Add New  <i class="fa fa-plus"></i></a>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.DisplayName)
                        </th>*@

                    <th>
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WebAddress)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        @*<td>
                                @Html.DisplayFor(modelItem => item.DisplayName)
                            </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WebAddress)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            <a href="@Url.Action("Edit","CompanyProfile",new { id = item.Id})"><i class="fa fa-pencil" title="Edit Company Profile"></i></a> <a href="@Url.Action("Delete","CompanyProfile",new { id = item.Id})" class="delete-row" title="Remove Company Profile" onclick="return confirm('Are sure wants to delete?');"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

<script src="~/assets/js/core/jquery.min.js"></script>
<script src="~/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>

<script src="~/assets/js/pages/base_tables_datatables.js"></script>