DMS/Models/DepartmentViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using RestSharp;
using DMS.Model;
using DMS.RestHelpers;
namespace DMS.Models
{
    public class DepartmentViewModel
    {
        [JsonProperty("Id")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter Department name"), MaxLength(130)]
        [JsonProperty("Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please select company")]
        [JsonProperty("CompanyId")]
        public int CompanyId { get; set; }

        [JsonProperty("CreatorId")]
        public int CreatorId { get; set; }
        [JsonProperty("CreateDate")]
        public DateTime CreateDate { get; set; }
        [JsonProperty("UpdatorId")]
        public int UpdatorId { get; set; }
        [JsonProperty("UpdateDate")]
        public DateTime UpdateDate { get; set; }
        public IList<CompanyProfile> CompanyProfiles { get; set; }
      
        public string GetCompanyNameByCompanyId(int companyId)
        {
            using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
            {
                var company = companyProfileRestHelper.GetCompanyProfileById(CompanyId);
                return company.Name;
            }
        }
    }
}

DMS/Controllers/Configurations/DepartmentController.cs
using AutoMapper;
using DMS.Extensions;
using DMS.Model;
using DMS.Models;
using DMS.RestHelpers;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace DMS.Controllers.Configurations
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            using (DepartmentRestHelper restHelper = new DepartmentRestHelper())
            {
                IList<Department> departments = new List<Department>();
                var response = restHelper.GetDepartments();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    departments = JsonConvert.DeserializeObject<List<Department>>(response.Content);
                    return View(departments);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View(departments);
                }
            }

        }


        // GET: Department/Create
        public ActionResult Create()
        {
            using (CompanyProfileRestHelper restHelper = new CompanyProfileRestHelper())
            {
                var response = restHelper.GetCompanyProfiles();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    DepartmentViewModel branchViewModel = new DepartmentViewModel
                    {
                        CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content)
                    };
                    return View(branchViewModel);
                }
                else
                {
                    this.AddNotification(response.Content, NotificationType.ERROR);
                    return View("Index");
                }

            }
        }

        // POST: Department/Create
        [HttpPost]
        public ActionResult Create(DepartmentViewModel departmentViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (DepartmentRestHelper restHelper = new DepartmentRestHelper())
                    {


                        var config = new MapperConfiguration(cfg => cfg.CreateMap<DepartmentViewModel, Department>());
                        var mapper = config.CreateMapper();
                        Department department = mapper.Map<Department>(departmentViewModel);

                        restHelper.AddDepartment(department);

                    }


                    this.AddNotification("Department created successfully!", NotificationType.SUCCESS);
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification("Some fields are required", NotificationType.WARNING);

                    CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper();
                    var response = companyProfileRestHelper.GetCompanyProfiles();
                    if (response.StatusCode == HttpStatusCode.OK)
                        departmentViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);

                    return View("Create", departmentViewModel);
                }


            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Department/Edit/id
        public ActionResult Edit(int id)
        {
            using (DepartmentRestHelper restHelper = new DepartmentRestHelper())
            {
                Department department = restHelper.GetDepartmentById(id);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Department, DepartmentViewModel>());
                var mapper = config.CreateMapper();
                DepartmentViewModel departmentViewModel = mapper.Map<DepartmentViewModel>(department);
                using (CompanyProfileRestHelper companyProfileRestHelper = new CompanyProfileRestHelper())
                {
                    var response = companyProfileRestHelper.GetCompanyProfiles();
                    if (response.StatusCode == HttpStatusCode.OK)
                        departmentViewModel.CompanyProfiles = JsonConvert.DeserializeObject<List<CompanyProfile>>(response.Content);

                }
                return View(departmentViewModel);
            }
        }

        // POST: Department/Edit/model
        [HttpPost]
        public ActionResult Edit(DepartmentViewModel departmentViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)

                {
                    using (DepartmentRestHelper departmentRestHelper = new DepartmentRestHelper())
                    {

                        var config = new MapperConfiguration(cfg => cfg.CreateMap<DepartmentViewModel, Department>());
                        var mapper = config.CreateMapper();
                        Department department = mapper.Map<Department>(departmentViewModel);


                        var response=departmentRestHelper.UpdateDepartment(department);

                        if (response.StatusCode == HttpStatusCode.OK)
                            this.AddNotification("Department profile updated successfully!", NotificationType.SUCCESS);
                        else
                            this.AddNotification(response.Content, NotificationType.ERROR);
                    }

                   

                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification("Error while update Department Profile:" + ex.Message, NotificationType.ERROR);
                return View();
            }
        }

        // POST: Department/Delete/id
        public ActionResult Delete(int id)
        {


            using (DepartmentRestHelper departmentRestHelper = new DepartmentRestHelper())
            {

                var response = departmentRestHelper.DeleteDepartmentById(id);
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    this.AddNotification("Department deleted successfully!", NotificationType.SUCCESS);
                    return RedirectToAction("Index");
                }
                else
                {
                    this.AddNotification("Something went wrong..", NotificationType.ERROR);
                    return RedirectToAction("Index");
                }
            }


        }
    }
}

DMS/Views/Department/Create.cshtml
@model DMS.Models.DepartmentViewModel


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2.min.css" />
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2-bootstrap.css" />
<style type="text/css">
    .text-danger {
        color: red;
        font-size: smaller;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card-header">
            <h4>Departments</h4>
            <hr />
            <ul class="card-actions">
                <li>
                    <button type="button"><i class="ion-more"></i></button>
                </li>
            </ul>
        </div>
        <div class="card-block">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Department Name..." } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <label class="control-label col-md-2">Company</label>
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.CompanyId, new SelectList(Model.CompanyProfiles, "Id", "Name"), "Select Company", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group m-b-0">
                <div class="col-md-9 col-md-offset-3">
                    <button class="btn btn-app" type="submit">Save</button>
                    <a href="@Url.Action("Index","Department")" class="btn btn-app-light">Cancel</a>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/assets/js/core/jquery.min.js"></script>
<script>
    $(function () {

        $("#CompanyId").selectize();

    });


</script>

DMS/Views/Department/Edit.cshtml
@model DMS.Models.DepartmentViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2.min.css" />
<link rel="stylesheet" href="~/assets/js/plugins/select2/select2-bootstrap.css" />



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="card">
            <div class="card-header">
                <h4>Department</h4>
                <hr />
                <ul class="card-actions">
                    <li>
                        <button type="button"><i class="ion-more"></i></button>
                    </li>
                </ul>
            </div>
            <div class="card-block">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Company</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.CompanyId, new SelectList(Model.CompanyProfiles, "Id", "Name"), "Select Company", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group m-b-0">
                    <div class="col-md-9 col-md-offset-3">
                        <button class="btn btn-app" type="submit">Save</button>
                        <a href="@Url.Action("Index","Department")" class="btn btn-app-light">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="~/assets/js/core/jquery.min.js"></script>
<script>
    $(function () {

        $("#CompanyId").selectize();

    });


</script>

DMS/Views/Department/Index.cshtml
@model IEnumerable<DMS.Model.Department>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/assets/js/plugins/datatables/jquery.dataTables.min.css" />



<div class="card">
    <div class="card-header">
        <h4>Departments</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md" style="margin-bottom:5px;">
                    <a href="@Url.Action("Create","Department")" id="addToTable" class="btn btn-app-teal">Add New  <i class="fa fa-plus"></i></a>
                </div>
            </div>
        </div>
      
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full"> 
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.CreateDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyId)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompanyName)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.CreateDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CompanyId)
                            </td>
                        <td>

                            <a href="@Url.Action("Edit","Department",new { id = item.Id})"><i class="fa fa-pencil" title="Edit Department"></i></a> <a href="@Url.Action("Delete","Department",new { id = item.Id})" class="delete-row" title="Remove Department" onclick="return confirm('Are sure wants to delete?');"><i class="fa fa-trash-o"></i></a>

                        </td>
                    </tr>
                    }
    </tbody>
</table>

        
       
    </div>
</div>
<script src="~/assets/js/core/jquery.min.js"></script>
<script src="~/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/assets/js/pages/base_tables_datatables.js"></script>